# in the repos, the key specifies the name of the temp directory name
repos:
  rw-generic-codecollection: https://github.com/runwhen-contrib/rw-generic-codecollection.git
robot_file_pattern:
  codebundles: .robot