version: '3'

# Taskfile for managing Azure Cosmos DB test infrastructure
# Install Task: https://taskfile.dev/#/installation
# Usage: task setup, task test, task cleanup

vars:
  RESOURCE_GROUP: rw-cosmosdb-test-rg
  LOCATION: eastus
  COSMOSDB_ACCOUNT: rw-cosmosdb-test-{{now | unixEpoch}}
  DATABASE_NAME: testdb
  CONTAINER_NAME: testcontainer
  PARTITION_KEY: /id

tasks:
  setup:
    desc: "Set up Azure Cosmos DB test infrastructure"
    cmds:
      - task: register-provider
      - task: create-resource-group
      - task: create-cosmosdb-account
      - task: create-database
      - task: create-container
      - task: populate-test-data
      - task: show-credentials

  register-provider:
    desc: "Register Microsoft.DocumentDB provider (required for Cosmos DB)"
    cmds:
      - |
        echo "Checking Microsoft.DocumentDB provider registration..."
        
        # Check if already registered
        STATUS=$(az provider show --namespace Microsoft.DocumentDB --query "registrationState" -o tsv 2>/dev/null || echo "NotFound")
        
        if [ "$STATUS" = "Registered" ]; then
          echo "✅ Microsoft.DocumentDB provider already registered"
        else
          echo "Registering Microsoft.DocumentDB provider..."
          az provider register --namespace Microsoft.DocumentDB
          
          echo "Waiting for registration to complete (this may take 1-2 minutes)..."
          az provider wait --namespace Microsoft.DocumentDB --created
          
          echo "✅ Microsoft.DocumentDB provider registered successfully"
        fi
    silent: false

  create-resource-group:
    desc: "Create Azure resource group"
    cmds:
      - |
        echo "Creating resource group {{.RESOURCE_GROUP}}..."
        az group create \
          --name {{.RESOURCE_GROUP}} \
          --location {{.LOCATION}} \
          --tags purpose=testing owner=runwhen
    silent: false

  create-cosmosdb-account:
    desc: "Create Azure Cosmos DB account"
    cmds:
      - |
        echo "Creating Cosmos DB account (this may take several minutes)..."
        az cosmosdb create \
          --name {{.COSMOSDB_ACCOUNT}} \
          --resource-group {{.RESOURCE_GROUP}} \
          --kind GlobalDocumentDB \
          --default-consistency-level Session \
          --locations regionName={{.LOCATION}} failoverPriority=0 isZoneRedundant=False \
          --enable-free-tier false
        
        # Save account name for later use
        echo "{{.COSMOSDB_ACCOUNT}}" > ./cosmosdb_account_name.txt
    silent: false

  create-database:
    desc: "Create Cosmos DB database"
    cmds:
      - |
        ACCOUNT_NAME=$(cat ./cosmosdb_account_name.txt)
        echo "Creating database {{.DATABASE_NAME}}..."
        az cosmosdb sql database create \
          --account-name $ACCOUNT_NAME \
          --resource-group {{.RESOURCE_GROUP}} \
          --name {{.DATABASE_NAME}} \
          --throughput 400
    silent: false

  create-container:
    desc: "Create Cosmos DB container"
    cmds:
      - |
        ACCOUNT_NAME=$(cat ./cosmosdb_account_name.txt)
        echo "Creating container {{.CONTAINER_NAME}}..."
        az cosmosdb sql container create \
          --account-name $ACCOUNT_NAME \
          --resource-group {{.RESOURCE_GROUP}} \
          --database-name {{.DATABASE_NAME}} \
          --name {{.CONTAINER_NAME}} \
          --partition-key-path {{.PARTITION_KEY}}
    silent: false

  populate-test-data:
    desc: "Populate test data using Python script"
    cmds:
      - |
        ACCOUNT_NAME=$(cat ./cosmosdb_account_name.txt)
        echo "Populating test data..."
        python3 ./populate_test_data.py \
          --account-name $ACCOUNT_NAME \
          --resource-group {{.RESOURCE_GROUP}} \
          --database {{.DATABASE_NAME}} \
          --container {{.CONTAINER_NAME}}
    silent: false

  show-credentials:
    desc: "Display Cosmos DB connection information"
    cmds:
      - |
        ACCOUNT_NAME=$(cat ./cosmosdb_account_name.txt)
        echo ""
        echo "========================================="
        echo "Cosmos DB Test Infrastructure Ready!"
        echo "========================================="
        echo ""
        echo "Account Name: $ACCOUNT_NAME"
        echo "Database: {{.DATABASE_NAME}}"
        echo "Container: {{.CONTAINER_NAME}}"
        echo ""
        echo "Endpoint:"
        az cosmosdb show \
          --name $ACCOUNT_NAME \
          --resource-group {{.RESOURCE_GROUP}} \
          --query documentEndpoint -o tsv
        echo ""
        echo "Primary Key (use as cosmosdb_key secret):"
        az cosmosdb keys list \
          --name $ACCOUNT_NAME \
          --resource-group {{.RESOURCE_GROUP}} \
          --query primaryMasterKey -o tsv
        echo ""
        echo "Set these as environment variables or secrets:"
        echo "  cosmosdb_endpoint=https://$ACCOUNT_NAME.documents.azure.com:443/"
        echo "  cosmosdb_key=<primary key from above>"
        echo "  DATABASE_NAME={{.DATABASE_NAME}}"
        echo "  CONTAINER_NAME={{.CONTAINER_NAME}}"
        echo ""
    silent: false

  test:
    desc: "Run Robot Framework tests"
    cmds:
      - task: test-syntax
      - task: test-integration

  test-syntax:
    desc: "Validate Robot Framework syntax"
    cmds:
      - |
        echo "Validating Robot Framework syntax..."
        python3 -m robot.libdoc RW.Azure.Cosmosdb ./Cosmosdb_keywords.html
        python3 -m robot --dryrun --output NONE --report NONE --log NONE runbook.robot
        python3 -m robot --dryrun --output NONE --report NONE --log NONE sli.robot
        echo "Syntax validation passed!"
    silent: false

  test-integration:
    desc: "Run integration tests (requires setup)"
    cmds:
      - |
        if [ ! -f ./cosmosdb_account_name.txt ]; then
          echo "ERROR: Test infrastructure not set up. Run 'task setup' first."
          exit 1
        fi
        ACCOUNT_NAME=$(cat ./cosmosdb_account_name.txt)
        echo "Running integration tests..."
        python3 ./run_integration_tests.py \
          --account-name $ACCOUNT_NAME \
          --resource-group {{.RESOURCE_GROUP}} \
          --database {{.DATABASE_NAME}} \
          --container {{.CONTAINER_NAME}}
    silent: false

  cleanup:
    desc: "Delete all test infrastructure"
    prompt: "This will delete the entire resource group '{{.RESOURCE_GROUP}}'. Continue?"
    cmds:
      - |
        echo "Deleting resource group {{.RESOURCE_GROUP}}..."
        az group delete \
          --name {{.RESOURCE_GROUP}} \
          --yes \
          --no-wait
        
        # Clean up local files
        rm -f ./cosmosdb_account_name.txt
        
        echo "Resource group deletion initiated (running in background)"
        echo "It may take a few minutes to complete."
    silent: false

  status:
    desc: "Check status of test infrastructure"
    cmds:
      - |
        if [ ! -f ./cosmosdb_account_name.txt ]; then
          echo "No test infrastructure found."
          exit 0
        fi
        
        ACCOUNT_NAME=$(cat ./cosmosdb_account_name.txt)
        echo "Checking status of Cosmos DB account: $ACCOUNT_NAME"
        echo ""
        
        az cosmosdb show \
          --name $ACCOUNT_NAME \
          --resource-group {{.RESOURCE_GROUP}} \
          --query "{name:name, status:provisioningState, endpoint:documentEndpoint}" \
          -o table || echo "Infrastructure not found or deleted"
    silent: false

  logs:
    desc: "View Cosmos DB metrics and logs"
    cmds:
      - |
        ACCOUNT_NAME=$(cat ./cosmosdb_account_name.txt)
        echo "Fetching recent metrics..."
        az monitor metrics list \
          --resource "/subscriptions/$(az account show --query id -o tsv)/resourceGroups/{{.RESOURCE_GROUP}}/providers/Microsoft.DocumentDB/databaseAccounts/$ACCOUNT_NAME" \
          --metric TotalRequests \
          --interval PT1H \
          --query "value[0].timeseries[0].data[-5:]" \
          -o table
    silent: false

  check-prerequisites:
    desc: "Check if prerequisites are installed and configured"
    cmds:
      - |
        echo "Checking prerequisites..."
        echo ""
        
        # Check Azure CLI
        if ! command -v az &> /dev/null; then
          echo "❌ Azure CLI not found. Install from: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
          exit 1
        fi
        echo "✅ Azure CLI installed: $(az --version | head -n1)"
        
        # Check Azure login
        if ! az account show &> /dev/null; then
          echo "❌ Not logged into Azure. Run: az login"
          exit 1
        fi
        SUBSCRIPTION=$(az account show --query name -o tsv)
        echo "✅ Logged into Azure subscription: $SUBSCRIPTION"
        
        # Check Python
        if ! command -v python3 &> /dev/null; then
          echo "❌ Python 3 not found"
          exit 1
        fi
        echo "✅ Python installed: $(python3 --version)"
        
        # Check azure-cosmos package
        if ! python3 -c "import azure.cosmos" &> /dev/null; then
          echo "⚠️  azure-cosmos package not installed. Install with: pip install azure-cosmos"
        else
          echo "✅ azure-cosmos package installed"
        fi
        
        # Check Robot Framework
        if ! command -v robot &> /dev/null; then
          echo "⚠️  Robot Framework not installed. Install with: pip install robotframework"
        else
          echo "✅ Robot Framework installed"
        fi
        
        echo ""
        echo "Prerequisites check complete!"
    silent: false

  help:
    desc: "Show help information"
    cmds:
      - |
        echo "Azure Cosmos DB Test Infrastructure Tasks"
        echo ""
        echo "Available tasks:"
        echo "  setup              - Create all test infrastructure (resource group, Cosmos DB, test data)"
        echo "  test               - Run syntax and integration tests"
        echo "  status             - Check status of test infrastructure"
        echo "  logs               - View Cosmos DB metrics"
        echo "  cleanup            - Delete all test infrastructure"
        echo "  check-prerequisites- Check if prerequisites are installed"
        echo "  register-provider  - Register Microsoft.DocumentDB provider (auto-run by setup)"
        echo ""
        echo "Typical workflow:"
        echo "  1. task check-prerequisites  # Verify setup"
        echo "  2. task setup                # Create infrastructure (takes ~5-10 minutes)"
        echo "  3. task test                 # Run tests"
        echo "  4. task cleanup              # Clean up when done"
        echo ""
        echo "Requirements:"
        echo "  - Azure CLI installed and authenticated (az login)"
        echo "  - Python 3.x with azure-cosmos package (pip install azure-cosmos)"
        echo "  - Robot Framework (pip install robotframework)"
        echo ""
        echo "First time setup issues?"
        echo "  If you see 'MissingSubscriptionRegistration', run:"
        echo "    task register-provider"
    silent: true

