name: Score CodeCollection
on: 
  workflow_dispatch:

jobs:
  score-codebundles:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # <-- This ensures we can push commits
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # so we can push back

      - name: Set Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - uses: runwhen-contrib/github-actions/codecollection-score@score
        with:
          directory: './codebundles'
          commit_results: true
